### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by antoniobrandao** [mrmrs/html#4]
Hello, http://ht-ml.cc/ seems to be down

**Comment by lachlanjc** [comment]
@mrmrs It's still down :(

**Comment by mrmrs** [comment]
@antoniobrandao somehow missed this original issue (my github feed is very noisy and it is really easy to miss things - my apologies)

I didn't reregister that domain but the project page now sits at http://mrmrs.io/html if you want to see it.

cc @lachlanjc

**Comment by lachlanjc** [comment]
@mrmrs Thanks!

**Comment by lachlanjc** [comment]
@mrmrs Oh, it looks like the README needs to be updated too

**Comment by mrmrs** [comment]
@lachlanjc Get out of my head! Already done :) a71632a

**Comment by lachlanjc** [comment]
@mrmrs :+1:

**Comment by antoniobrandao** [comment]
Sorry, it's apparently not done really :D lol

Where it says "To view this unstyled markup visit http://mrmrs.io/html"

The hyperlink actually is pointing to http://mrmrs/io/html (which doesn't open) instead of http://mrmrs.io/html 

In the hyperlink value there is a slash where a dot should be.

**Comment by mrmrs** [comment]
@antoniobrandao I am the worst. Should be fixed now.

**Comment by antoniobrandao** [comment]
happens to everyone! & thanks
